name: Artifactory Terraform Upload & Xray Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  iac-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest

      - name: Configure JFrog CLI
        run: |
          jfrog config add artifactory \
            --url=${{ secrets.JF_URL }} \
            --access-token=${{ secrets.JF_ACCESS_TOKEN }} \
            --interactive=false

      - name: Upload Terraform Files to Artifactory
        run: |
          jfrog rt upload "*.tf" tf_iac_template-terraform/iac/${GITHUB_REPOSITORY}/${GITHUB_SHA}/ --recursive=false --server-id=artifactory

      - name: Run IaC Scan (Terraform + Secrets)
        run: |
          jfrog xr scan . --fail=false --output sarif --format json

      # - name: Upload SARIF report (Optional)
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: result.sarif